# Generated by Django 4.1.13 on 2024-04-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalClinica',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=3)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.personalclinica')),
            ],
        ),
    ]
