# Generated by Django 4.1.13 on 2024-04-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0003_propietariomascota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietariomascota',
            name='direccion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
