# Generated by Django 4.1.13 on 2024-04-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0004_propietariomascota_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
