# Generated by Django 4.1.13 on 2024-05-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0005_mascota_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('codAyuda', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAyuda', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idMedicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('presentacion', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField()),
                ('estado', models.IntegerField(default=1)),
                ('cedulaMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.personalclinica')),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('codProcedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProcedimiento', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProcedimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(null=True)),
                ('asistenciaEspecializada', models.CharField(max_length=30)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.orden')),
                ('idProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('dosis', models.CharField(max_length=30)),
                ('tiempoTratamiento', models.IntegerField(default=0)),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.medicamento')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenAyudaDiagnostica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(null=True)),
                ('asistenciaEspecializada', models.CharField(max_length=30)),
                ('revision', models.BooleanField(default=False)),
                ('idAyuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.ayuda')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.orden')),
            ],
        ),
    ]
